-- Step 2 schema only. Do not commit a seed containing note texts to this public repo.
-- Execute once in the dedicated learning Supabase project's SQL Editor.
create table if not exists public.training_notes (
  id bigint generated by default as identity primary key,
  owner_id uuid null,
  sort_order integer not null unique check (sort_order between 1 and 4),
  title text not null,
  content text not null
);

alter table public.training_notes enable row level security;
-- Never allow clients using anon/authenticated roles to read or modify the table.
revoke all on table public.training_notes from anon, authenticated;
revoke all on sequence public.training_notes_id_seq from anon, authenticated;
grant select on table public.training_notes to service_role;
-- No RLS SELECT policy for anon or authenticated.
-- Add only synthetic rows using a private SQL Editor script, not GitHub.
